import './App.ts';
import './Background.ts';
import './Terminal.ts';
import './TerminalInput.ts';
import './TerminalResponseItem.ts';
import './TerminalSection.ts';
import './components/PixelBorder.ts';
import './terminal/commands/pong/component.ts';
import './terminal/commands/snake/component.ts';
